
<h3>Benutzer Information editieren</h3>

<?php if ($this->error): ?>
<p class="error">
    There were one or more isues with your submission. Please correct them as 
    indicated below.
</p>
<?php endif ?>
<section>
<?php 
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('users/user-manager', array('action' => 'process')));
$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);
?>
<dl class="zend_form">
<dt><?php echo $this->formLabel($form->get('name')); ?></dt>
<?php echo $this->formElement($form->get('id')); ?>

<dd><?php 
    echo $this->formElement($form->get('name'));
    echo $this->formElementErrors($form->get('name'));
?></dd>

<dt><?php echo $this->formLabel($form->get('email')); ?></dt>
<dd><?php 
    echo $this->formElement($form->get('email'));
    echo $this->formElementErrors($form->get('email'));
?></dd>

<dd><?php 
    echo $this->formElement($form->get('submit'));
    echo $this->formElementErrors($form->get('submit'));
?></dd>

</dl>
<?php echo $this->form()->closeTag() ?>
</section>
