<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Club des Champions'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>


	</head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('users') ?>"> <?php echo $this->translate('Club des Champions') ?></a>
                    <div class="nav-collapse ">
                        <ul class="nav navbar-nav">
                            <li class="<?php echo $this->x_active; ?>"><a href="<?php echo $this->url('users') ?>"><?php echo $this->translate('Start') ?></a></li>
                            <li class="<?php echo $this->login_active; ?>"><a href="<?php echo $this->url('users/login') ?>"><?php echo $this->translate('Anmeldung') ?></a></li>
                            <li class="<?php echo $this->register_active; ?>"><a href="<?php echo $this->url('users/register') ?>"><?php echo $this->translate('Registrierung') ?></a></li>
							<li class="<?php echo $this->dokumentation_active; ?>"><a href="<?php echo $this->url('users/dokumentation') ?>"><?php echo $this->translate('Dokumentation') ?></a></li>                     
							
						</ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
			
			<a href="http://champion.local/users"><img src="../img/camer.jpg"  width="350" height="200" /></a>
            <hr>
            <footer>
                <p>&copy; <?php echo date('Y') ?> by <b>Baduma</b>. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
