<h3>Send Offline Message</h3>
<?php 
// Render the opening tag
echo $this->form()->openTag($form);

// ...loop through and render the form elements...

echo 'From : '. $userName .''; echo '<br><br>';

foreach ($form as $element) {


	echo $this->formLabel($element);               // <-- Magic!
    echo $this->formElement($element);         echo '<br>';     // <-- Magic!
    echo $this->formElementErrors($element);   echo '<br>';
}

// Render the closing tag
echo $this->form()->closeTag();

?>